
Project: ProjectName
Version: 1.0

API:
  Production:
    Address: 0.0.0.0
    Port: 8080
  Management:
    Address: 0.0.0.0
    Port: 9090

Database:
  DBMS: mysql
  Address: 127.0.0.1
  Port: 3306
  Schema: grestdb
  Username: root
  Password: root
